### ISSUE TITLE
not working on thunderbird verstion 86.0b1

### ISSUE THREAD

**Issue by bonbonbillo** [thundernest/import-export-tools-ng#205]
not working on thunderbird verstion 86.0b1

**Comment by cleidigh** [comment]
@bonbonbillo 
you are correct, the extension officially supports 68-78
I am not currently working on supporting the beta 86
not exactly sure when I will be working on that
Christopher

**Comment by blono** [comment]
The code is almost like a template, so I have the same problem with multiple add-ons :)
I've fixed it in the repository here for your reference!
https://github.com/protz/Manually-Sort-Folders/issues/140

**Comment by jobisoft** [comment]
Hi Christopher,

if you want, you can update your WL API from here:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis/WindowListener

There will be another change which I am still working on, and I did not want to hassle add-on devs to update multiple times, so I did not announce the update yet. But if you want beta users to be able to use import-export tools, you can of course update now already.

Do you have a custom version of the WL API due to your tab-content overlays, or do you have that code in your custom injector script for the main messenger window? I started to use the mailTab interface to hook into those, instead of a mutation observer. For example:

```
  getAddonManager(window) {
    // Check if add-on manager is open.
    let tabMail = window.document.getElementById("tabmail");
    for (let tabInfo of tabMail.tabInfo) {
      let tabWin = tabInfo.browser.contentWindow;
      if (tabWin && tabWin.location.href == "about:addons") {
        return tabWin;
      }
    }
  }
```

That interface also has a monitor, which I am currently investigating. I keep you posted, if you wish.

**Comment by cleidigh** [comment]
hey John

I will follow-up tomorrow with more

I have been banging my head because Fluent has issues on 68 as well as 
other issues seventy eight

I will elaborate tomorrow

I assume you're thinking updating WL for 86?

I am still dealing with 78 issue still I am not yet addressing 86

I should probably do a quick test

**Comment by jobisoft** [comment]
Closing in favor of
https://github.com/thundernest/import-export-tools-ng/issues/264
