### ISSUE TITLE
Problem importing EML files with structure

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#42]

**Comment by buggyboy** [comment]
I think I get same issue as reported there : https://github.com/thundernest/import-export-tools-ng/issues/41
trying to import eml from WLM and all I get is an empty folder structure, no file at all.  That's on Windows 10 x64 Home 1909, TB 68.2.2 32bits

This WLM has, in addition to a few mail accounts,  a lot of local folders on several levels.  
A local folder is created in TB, then menu (also tried with context menu) "Import/Export etc"/"Import all eml"/"Include subfolders" (bad translation from French)

Please let me know if I can provide other useful details.

**Comment by Jerry46151** [comment]
Conversion project not going well.  
Using Thunderbird 68.2.2 (32-bit) with ImportExporttools NG.  

Used BitRecover PST Converter to export Office 365 Exchange to eml

The first time it created maybe a dozen folders with no emails and quit.  Additional trys would do one or maybe a few folders with no emails and quit.
The folder structure look like this.
Afolder - (no eml files) sub folders have no sub folders, some sub folders are empty
     CompanyA - eml files
     CompanyB - eml files
     CompanyC - empty
     CompanyD - eml files
93 folders

**Comment by cleidigh** [comment]
@buggyboy 
@Jerry46151 
I do not seem to be getting notifications on their sorry for the delay.

I have done several support issues relating to this, including very large imports successfully.
So we have to figure out what's different.  Keep in mind that  personally do not have real experience with WLM.  

Under tests I have started to create several test trees for import testing.  There is a LiveMail
folder with a EML set of files.  It would be good to know if you both can import that successfully.
Also either with that or your own files, capturing and posting the debug log (Shift-Control-J)
maybe helpful to catch errors.

Let me know your progress...
https://github.com/thundernest/import-export-tools-ng/blob/import-tests/tests/import.zip

**Comment by cleidigh** [comment]
@buggyboy 
Can you describe what you mean by the "local folders" that you deleted?

**Comment by Jerry46151** [comment]
I fix my issue by turning the antivirus off.

Thanks

**Comment by Jerry46151** [comment]
I fixed my issue by turning the antivirus off.

Thanks

**Comment by cleidigh** [comment]
@Jerry46151 
Great!  This is a good thing to be aware of.  Was there anything that led you to do that?  I can imagine some thrashing between an antivirus program and Thunderbird for processing so many files.

**Comment by buggyboy** [comment]
These 2 screenshots show what I meant when talking about "local folders", basically first level stuff in the tree that is not a mail box, the same concept exist in both TB and WLM:
- https://drive.google.com/open?id=1YanYsfOQpIEM83Tl_GHWwBBKexDAqrBI
- https://drive.google.com/open?id=1nG80HbVOdBJcnTrxGlCUfuJ3apaTUC7M

This other Screenshot showsthe debug log, where, then again, the folder structure was imported but not the messages, and the log show an error message.  This tests was done without an antivirus (I had deactivated all built-in Windows 10 AV, as far as I can tell) :  https://drive.google.com/open?id=1mw_qopx0vNzpse3vyMZn8J2bkbNgAjXm

Importing your test import structure worked fine, 6 mails were imported.

**Comment by cleidigh** [comment]
@buggyboy 
It's not clear to me yet if by removing some of the files WLM creates did or did not solve the problem?
Also does the file structure you have to generally match my test files?
I just had someone go through updating/importing WLM files on over one thousand workstations so we are probably missing something basic.

**Comment by buggyboy** [comment]
Yes, removing some files "solves" the problem. Well, I can do a partial import then, but I need a full import, so it is not a real valid "solution".  It just shows that I can import some stuff, but not what I need.

as to the file structure, in mine there is a big mess in the "local folders", i.e. many sub-levels (it was created by a friend I'm trying to help). We might be running into file paths that are too long, for example, but I have no way to know.  Or a limit on the number of sublevels? Or a limit on the total number of files?

**Comment by cleidigh** [comment]
@buggyboy 
I do not believe the extra files would be a problem, I think they should just be ignored, I may need to add some more debugging information to catch what's going on.
Regardless, it would be good to try a small subset of files.
Since you appear to have a significant import you can actually easily break that up by selecting sets of folders to keep each import to a smaller size.
I would like to eliminate the quantity as a problem and make sure we can import subsets without a problem.

**Comment by buggyboy** [comment]
I did the following test 
- copy only the folders of the WLM folder structure into an then empty folder structure
- then copy a sample .eml file in all empty subfolders
- then try to import this almost empty folder structure

In TB, I then get the folder structure, but no mail imported.

I did this again, after having deleted a big chunk of the "almost empty" folder structure (the part related to local storage), and the I get test mails imported correctly.

This seems to prove that the problem is with the folder structure. Not with the number of mails, or the antivirus

**Comment by buggyboy** [comment]
I sent you  by email a copy of the folder structure, with one .eml file in each subfolder

**Comment by cleidigh** [comment]
@buggyboy 
Somehow I still don't get all The Notifications, can you tell me the subject line of the e-mail because I did not see it.

**Comment by buggyboy** [comment]
Fwd: Re: [thundernest/import-export-tools-ng] Problem importing EML files with structure (#42)

I just resent it

**Comment by cleidigh** [comment]
@buggyboy 
Still don't see the e-mail
cleidigh@gmail.com ?

**Comment by cleidigh** [comment]
@buggyboy 
some progress!
I finally got the old WLM to export a basic folder structure.
For the first time I got a new error referencing creating subfolders.
The end result matches yours, foldersno e-mail.
I have to look at recent changes as this was working before.
at least now I have something to go on

**Comment by buggyboy** [comment]
great, thanks for the update !

**Comment by cleidigh** [comment]
arrg
it is inconsistent
just imported the same folder structure successfully
...

**Comment by buggyboy** [comment]
did you get a chance to try with the folder structure I sent you?

**Comment by cleidigh** [comment]
@buggyboy 
after more tests with your set as well as my own , I now have an isolated model that generates errors on subfolder creation.  It is completely opaque to the extension , will have to pursue with the team.

**Comment by buggyboy** [comment]
thank you, please keep me updated.
What team do you mean?

**Comment by cleidigh** [comment]
I am the extension developer liaison but their core team members who know and work with the internals.  I'm working to get them to take a look.  I am still trying to find a workaround but no luck yet.

**Comment by cleidigh** [comment]
@buggyboy 
Progress!  see #57 
When I have a beta will you be able to test?
Thanks
Happy Holidays!

**Comment by buggyboy** [comment]
Happy Holidays to you too !

Yes, send a beta, I will test it.

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by ioneater** [comment]
fyi I run into the same problem today with a longish file path:
"C:\Users\USERNAME\AppData\Local\Microsoft\Windows Live Mail\Storage Folders (1)\XYZ\ASD\Storage Folders\Importierte 631\Lokale Ordner\"
After moving all sub directories to "C:\Lokale Ordner\" import worked without issues

**Comment by cleidigh** [comment]
@ioneater 
This is probably an issue with the final path exceeding the Windows limit of 250 characters.
Windows live Mail appears to like long paths.
I am curious . did you look at the debug console? (Control-Shift-J)
I am in the process of finding a check for this.

**Comment by ioneater** [comment]
@cleidigh 
I have no access to the original computer at the moment but reproduced the issue locally.
This is what the debug console displays after a failed import:

`TypeError: msgFolder is undefined` `mboximport.js:1041:4`
`buildEMLarray chrome://mboximport/content/mboximport.js:1041`
`RUNimportALLasEML chrome://mboximport/content/mboximport.js:1011`
`importALLasEML chrome://mboximport/content/mboximport.js:1004`
