### ISSUE TITLE
Export stops after a few messages

### ISSUE THREAD

**Issue by simonNath** [thundernest/import-export-tools-ng#98]
Hey there,

I've got a huge inbox (20000 messages) which I want to export. I select them, and choose Extras->NG->Export all messages ->with HTML index -> HTML with attachments. 

The process starts, but ends abruptly after 279 messages. The status message in the left down corner disappears, and nothing happens. I tried different locations, and different filename settings, but got no success. What is the cause?

Thanks
Nils

**Comment by cleidigh** [comment]
@simonNath 
thanks for the post, sorry for the issues...
I have been working on several issues related to large operations.  unfortunately this is been a slow painful process where I have not found the root cause.
couple of questions:
- can you identify the versions of OS, Thunderbird et cetera
- can you open and copy the Debug output (Shift Control J)
- if you could just comment on the folder structure, curious about the depths of folders, I have been looking as a possible issue 
@cleidigh

**Comment by wycomax** [comment]
It seems like this is still an open issue. I have a folder with almost 30000 messages. Doesn't matter which of the three options "XXXX export with attachments" I am using, if there is a message with an embedded image then the export script stops and Thunderbird needs a restart. It would be better if there was an option to skip "unexportable" emails and continue with the export job. Ideally the skipped emails would be reported in a textfile at the end. My environment: Thunderbird version 68.10.0 on Ubuntu. Script error happens at chrome://mboximport/content/exportTools.js:1310

**Comment by cleidigh** [comment]
@wycomax 
I have done several fixes for in-line images so I'm a bit surprised.
Your post implies that Any message with an in-line image causes an error, the size of the export does not matter yes ?  if this is the case to you possibly have an example message that is okay to send me?  you can always change any personal details so long as you maintain format.
I totally agree with you that a log would help, I am slowly trying to improve these things.

if you can clarify what your version of the extension you are using
also if you might posted the exact error you reference
thanks
Christopher

**Comment by cleidigh** [comment]
@wycomax 
attached is a zip where I created you couple of e-mails one with image attachment, one was an in-line image
I exported to HTML with attachments and also to EML.  I then reimported the EML 's
see if you are able to do the same.
While do not yet have your debug output, that particular line has to do with Unicode conversion
so we might be dealing with an encoding quirk
the goalless for both of us to get the same results 
Christopher
[EMLwimages.zip](https://github.com/thundernest/import-export-tools-ng/files/5252565/EMLwimages.zip)

**Comment by cleidigh** [comment]
@wycomax 
there is a possibility a converter change is the issue 
attached are two test versions
b15x1 has more output but still uses scriptable converter
b15x2 utilizes the new text decoder
if you can try to post the output that would be great
Christopher
[import-export-tools-ng-10.0.0-b15x2-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5252779/import-export-tools-ng-10.0.0-b15x2-tb.zip)
[import-export-tools-ng-10.0.0-b15x1-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5252780/import-export-tools-ng-10.0.0-b15x1-tb.zip)

**Comment by wycomax** [comment]
@cleidigh 
Thanks a lot for your quick reply. I found an example message which I have slightly edited. If I re-send the email to my mailbox, then the export function works fine. Only the original mail makes problems. Interestingly there are 2 different charsets mentioned in the email. Don't know if this could be normal or not.
$ grep -i charset  TST
	charset=ISO-8859-1;
	charset=US-ASCII;

[TST.zip](https://github.com/thundernest/import-export-tools-ng/files/5255069/TST.zip)

**Comment by wycomax** [comment]
> @wycomax
> attached is a zip where I created you couple of e-mails one with image attachment, one was an in-line image
> I exported to HTML with attachments and also to EML. I then reimported the EML 's
> see if you are able to do the same.
> While do not yet have your debug output, that particular line has to do with Unicode conversion
> so we might be dealing with an encoding quirk
> the goalless for both of us to get the same results
> Christopher
> [EMLwimages.zip](https://github.com/thundernest/import-export-tools-ng/files/5252565/EMLwimages.zip)

This worked for me, I could do successfully export and import these emails.

**Comment by wycomax** [comment]
> @wycomax
> there is a possibility a converter change is the issue
> attached are two test versions
> b15x1 has more output but still uses scriptable converter
> b15x2 utilizes the new text decoder
> if you can try to post the output that would be great
> Christopher
> [import-export-tools-ng-10.0.0-b15x2-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5252779/import-export-tools-ng-10.0.0-b15x2-tb.zip)
> [import-export-tools-ng-10.0.0-b15x1-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5252780/import-export-tools-ng-10.0.0-b15x1-tb.zip)
> 
> Note you can load a zip just as xpi same format

I installed both versions but nothing changed, the export HTML with Attachments didn't work. Where can I find the "output"?

**Comment by cleidigh** [comment]
@wycomax 
you get the error,Console with  shift- control-J, open this window then do the import goto the window
right-click to get the pop-up menu , select all, copy and post here
we should get something about the error you referenced before

**Comment by wycomax** [comment]
[b15x1] 
Handler function threw an exception: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsICacheInfoChannel.isRacing]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/server/actors/network-monitor/network-response-listener.js :: NetworkResponseListener.prototype._getSecurityInfo< :: line 334"  data: no]
Stack: NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/server/actors/network-monitor/network-response-listener.js:334:26
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22
onStartRequest@resource://devtools/server/actors/network-monitor/network-response-listener.js:226:10
Line: 334, column: 0 2 ThreadSafeDevToolsUtils.js:90:13
    reportException resource://devtools/shared/ThreadSafeDevToolsUtils.js:90
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:117
    onStartRequest resource://devtools/server/actors/network-monitor/network-response-listener.js:226
nsIScriptableUnicodeConverter exportTools.js:1311:17
BeforeConverter exportTools.js:1315:17
after converter exportTools.js:1317:17
save attachment done Picture%208.png exportTools.js:1330:17
Error: Script terminated by timeout at:
exportAsHtml/onStopRequest68/<@chrome://mboximport/content/mboximport/exportTools.js:1349:17
onStopRequest@resource:///modules/gloda/mimemsg.js:100:28
exportTools.js:1349:17
Navigated to chrome://extensions/content/dummy.xul
Start overland

[b15x2]
decoder exportTools.js:1322:17
save attachment done Picture%208.png exportTools.js:1330:17
Error: Script terminated by timeout at:
exportAsHtml/onStopRequest68/<@chrome://mboximport/content/mboximport/exportTools.js:1349:17
onStopRequest@resource:///modules/gloda/mimemsg.js:100:28
exportTools.js:1349:17

**Comment by cleidigh** [comment]
@wycomax 
that's good  it shows a timeout have never seen before
I just have to be to reproduce it here so I can really debug
I will try the  e-mail you sent
another possibility is for you to extract the e-mail from the database which might allow me to reproduce it

**Comment by cleidigh** [comment]
@wycomax 
as I expected importing your e-mail and exporting have no problems like your experiments
I think I know the best way to try and allow me to reproduce it, we have to get the raw database
message so that I have essentially exactly what you have
the easiest way to do this is copy the message into local folder then go to the file system under the profile
and we can get that folder directly.  you need to identify where your profile is, then go to Mail/Local Folders
 and then find the folder with the message zip everything and post
I am hoping that way I get the message as you have it to reproduce the problem

**Comment by cleidigh** [comment]
@wycomax 
I also tested another person sending e-mail with an in-line image from Apple Mail / looks very similar to yours but no problem 
I think the encoding information is okay 
something seems to be corrected when you send it or have it in the form what you sent me
is there anything on your side that you can think of in terms of experiments?
Christopher

**Comment by cleidigh** [comment]
@wycomax 
I thought of another experiment
try the following  extension for removing the attachment
we might learn something if it works
but my above comments are still standing

saveAttachmentToFile

**Comment by wycomax** [comment]
I installed Thunderbird on a Windows VM incl. b15x1
I created a local folder, imported the TST email and faced the same problem 
but the output in the error console is different: there is an explanation for the timeout:
---
05:03:38.075 nsIScriptableUnicodeConverter exportTools.js:1311:17
05:03:38.076 BeforeConverter exportTools.js:1315:17
05:03:38.076 after converter exportTools.js:1317:17
05:03:38.077 save attachment done Picture%208.png exportTools.js:1330:17
05:03:45.921
InternalError: too much recursionexportTools.js:1349:17
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    onStopRequest68 chrome://mboximport/content/mboximport/exportTools.js:1349
    onStopRequest resource:///modules/gloda/MimeMessage.jsm:95

**Comment by wycomax** [comment]
Sorry for big bold letters, I didn't format it like that... happened automatically

**Comment by wycomax** [comment]
Attached you'll find my Local Folder Test4Github which I didn't export. I created a tar-file directly from the content and zipped it.
[Test4Github.tar.gz](https://github.com/thundernest/import-export-tools-ng/files/5259044/Test4Github.tar.gz)

**Comment by cleidigh** [comment]
@wycomax 
excellent, I think that did it. I have yet to reproduce the exact error because my system locks up when  I try to export after successfully importing the mbox.  I also see that it appears to have an issue earlier.
I am trying to get a stable debug scenario
the issue appears to be more subtle than I understood

**Comment by cleidigh** [comment]
@wycomax 
b15 should fix the issue however I really don't know the root cause but the end result appears to be timeouts and recursion
hopefully this is good as I would really like to release
link at the top of the thread

**Comment by wycomax** [comment]
@cleidigh 
I trust that you will find the error soon

**Comment by cleidigh** [comment]
@wycomax 
were you able to try b15? it solves the problem on my side.

**Comment by wycomax** [comment]
Oh, sorry for misunderstanding! I thought you mean b15x1 and b15x2 which didn't solve the problem. How to use b15? I found the file exportTools.js but how/where to install it?

**Comment by wycomax** [comment]
@cleidigh 
Sorry, I got you wrong... I just have installed b15 and the testcase worked fine for me. Thank you so much! Will try to export the complete folder now where I found these kind of messages.

**Comment by cleidigh** [comment]
@wycomax 
that's excellent Andreas, I really appreciate the time you took testing!
unfortunately sometimes it's the only way to figure things out.
I will check out the status exit button, probably botch something with all the other work.
the whole status message operation is one of many needed improvements.
I'm going to jump cleanup and then finally release.
cheers
Christopher

**Comment by cleidigh** [comment]
fixed wb15

**Comment by cleidigh** [comment]
@wycomax 
I tested several exports and I always see the button up to the point it is finished, then just text for five seconds.
did you just miss it?

**Comment by wycomax** [comment]
@cleidigh 
Yes, you are right, now I can see the button too. Maybe I forgot to restart TB after I installed b15, not sure... But ok, then this is also solved :+1:

**Comment by cleidigh** [comment]
actually what I did just see is that on the import EML the original extension does not show the import icon
I am fixing now
